# What is Numpy

 Numpy 수치해석용 Python 패키지.
 다차원 배열 자료구조 클래스 ndarray 지원 및 벡터 행렬 연산
 tensorflow 및 딥러닝 패키지 데이터 연산시 사용
 
 * Python list
     * 원소 갯수 변경 가능
     * 다른 자료형 사용 가능
     * 메모리 차지 및 속도가 느림


 * Numpy ndarray
     * 원소 갯수 변경 불가
     * 모든 원소가 같은 자료형
     * 메모리 사용량이 적고 속도가 빠름
 
 
 * 목차
     * Numpy 데이터 타입
     * Numpy 배열 생성
     * Numpy 연산
     * Numpy 브로드캐스팅 
     * Numpy 슬라이싱
     * Numpy 배열 변환 
     

In [1]:
print ("========list example========")
list = [0,1,2,4]
print (list)

list[2] = 'foo'
print (list)

list.append('bar')
print (list)

list.pop()
print (list)


========list example========
[0, 1, 2, 4]
[0, 1, 'foo', 4]
[0, 1, 'foo', 4, 'bar']
[0, 1, 'foo', 4]


In [2]:
import numpy as np

print ("========numpy example========")
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print (type(a))
print (a.ndim)
print (a.shape)
print (a[1], a[3], a[5])
a[5] = 12
print (a)

b = np.array([[1,2,3],[11,12,13]])
print (b.ndim)
print (b.shape)
print (b[0,0], b[1,0], b[-1,-1], b[1, 2])

========numpy example========
<type 'numpy.ndarray'>
1
(10,)
(1, 3, 5)
[ 0  1  2  3  4 12  6  7  8  9]
2
(2, 3)
(1, 11, 13, 13)


## Numpy 데이터 타입

numpy의 자료형은 dtype을 사용
dtype에 따른 데이터를 numpy 배열로 할당
 * ?: boolean
 * b: byte
 * i: int
 * u: unsigned int
 * f: float
 * o: object pointer
 * S, 'a': zero teminated bytes(not recommended)
 * U: unicode string
 * c: complex-floating point
 * v: void(raw data)


In [3]:
print ("========i4========")
dt = np.dtype('i4') # 32 bit signed int
print (dt.itemsize)
print (dt.name)

print ("========np.int32========")
dt = np.dtype(np.int32) # 32 bit signed int
print (dt.itemsize)
print (dt.name)

print ("========f8========")
dt = np.dtype('f8') # 64 bit floating point
print (dt.itemsize)
print (dt.name)

print ("========c16========")
dt = np.dtype('c16') # 128 bit complex floating point
print (dt.itemsize)
print (dt.name)

print ("========U2========")
dt = np.dtype('U2') # 25-character string
print (dt.itemsize)
print (dt.name)

========i4========
4
int32
========np.int32========
4
int32
========f8========
8
float64
========c16========
16
complex128
========U2========
8
unicode64


## Numpy 배열 생성
numpy 배열 생성 방법
 * 특정 값으로 초기화
 * 단위 행렬 생성
 * 구간 분활
 * random 초기화

In [4]:
print ("========zeros========")
a = np.zeros(5) 
print (a)

a = np.zeros((3,4), dtype="f8")
print (a)

a = np.zeros(5, dtype="U4")
a[0] = "hello"
a[1] = "helo"

print (a)

print ("========ones========")
a = np.ones((3,4), dtype="f8")
print (a)

print ("========full========")
a = np.full((3,4), 9, dtype="f8")
print (a)

print ("========eye========")
a = np.eye(3) # 단위 행렬 생성
print (a)

========zeros========
[ 0.  0.  0.  0.  0.]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[u'hell' u'helo' u'' u'' u'']
========ones========
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
========full========
[[ 9.  9.  9.  9.]
 [ 9.  9.  9.  9.]
 [ 9.  9.  9.  9.]]
========eye========
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [5]:


#리스트의 크기만 큼 numpy 행렬 생성
print ("========ones_like========")
list = range(10)
print (list)
a = np.ones_like(list, dtype="f")
print (a)
print ("========zeros_like========")
a = np.zeros_like(list, dtype="f")
print (a) 

print ("========arange========")
a = np.arange(10)
print (a)

a = np.arange(2,23,5) # (start idx, last idx, stride)
print (a)

print ("========linspace========")
a = np.linspace(10,210,11)  # (start idx, last idx, divide num)
print(a)

print ("========logspace========")
a = np.logspace(0,5,6)  # (start idx, last idx, divide num), 10^0 ~ 10^5
print(a)

print ("========rand========")
a = np.random.rand(4) + 0.5
print (a)

========ones_like========
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
========zeros_like========
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
========arange========
[0 1 2 3 4 5 6 7 8 9]
[ 2  7 12 17 22]
========linspace========
[  10.   30.   50.   70.   90.  110.  130.  150.  170.  190.  210.]
========logspace========
[  1.00000000e+00   1.00000000e+01   1.00000000e+02   1.00000000e+03
   1.00000000e+04   1.00000000e+05]
========rand========
[ 0.62960183  0.64586342  1.03266306  1.04684763]


## Numpy 연산

numpy를 이용한 기본적인 연산
* 더하기, 곱하기, 나누기
* log
* 내적 </br>
![title1](./matrix_product2.jpg)
* 행렬 합, 평균, 최대값, 최소값
* 행렬 최대 최소값 index
* 행렬 정렬
* 행렬 비교

In [6]:
x = np.array([[1,2],[3,4]], dtype='f4')
y = np.array([[5,6],[7,8]], dtype='f4')
z = [[1,2,], [3,4]]

print ("========calculation========")
print (z*2)
print (x*2)
print (np.exp(x))
print (np.log(x))
print (np.log10(x))


========calculation========
[[1, 2], [3, 4], [1, 2], [3, 4]]
[[ 2.  4.]
 [ 6.  8.]]
[[  2.71828175   7.38905621]
 [ 20.08553696  54.59814835]]
[[ 0.          0.69314718]
 [ 1.09861231  1.38629436]]
[[ 0.          0.30103001]
 [ 0.47712123  0.60206002]]


In [7]:
print (x + y)
print (x - y)
print (x * y)
print (x / y)
print (np.sqrt(x))

#벡터 내적
print ("========dot product========")
print (x.dot(y))
print (np.dot(x,y))

[[  6.   8.]
 [ 10.  12.]]
[[-4. -4.]
 [-4. -4.]]
[[  5.  12.]
 [ 21.  32.]]
[[ 0.2         0.33333334]
 [ 0.42857143  0.5       ]]
[[ 1.          1.41421354]
 [ 1.73205078  2.        ]]
========dot product========
[[ 19.  22.]
 [ 43.  50.]]
[[ 19.  22.]
 [ 43.  50.]]


In [8]:
print ("========sum========")
print (np.sum(x))
print (np.sum(x, axis=0)) #각 열에 대한 합 반환, axis 0를 무시하고 합 연산 
print (np.sum(x, axis=1)) #각 행에 대한 합 반환, axis 1를 무시하고 합 연산

print ("========min max========")
print (np.min(x))
print (np.max(x))
print (np.max(x, axis=0) )#각 열에 대한 최대값 반환

print ("========argmin argmax========")
print (np.argmin(x))# 최소값 index 반환
print (np.argmax(x))# 최대값 index 반환
print (np.argmax(x, axis=0))
print (np.argmin(x, axis=1))

print ("========mean========")
print (np.mean(x))



========sum========
10.0
[ 4.  6.]
[ 3.  7.]
========min max========
1.0
4.0
[ 3.  4.]
========argmin argmax========
0
3
[1 1]
[0 0]
========mean========
2.5


In [9]:
print ("========all any========")
a = np.ndarray([0, 1])
print (np.all([True, True, False]))
print (np.all([True, True, True]))
print (np.any([True, True, False]))
print (np.any([False, False, False]))
print (np.any(a == 1))
print (np.all(a == 1))

print ("========where========")
x = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print (np.where(x < 6)) # return x position, y position
print (np.argwhere(x < 6))

print ("========compare========")
print (a)
print (a==1)
print (a>2)
print ((a==1) | (a>2))
a[:][(a==1) | (a>2)] = -1
print (a)

========all any========
False
True
True
False
False
True
========where========
(array([0, 0, 0, 1, 1]), array([0, 1, 2, 0, 1]))
[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]]
========compare========
[]
[]
[]
[]
[]


In [10]:
a = np.array([[2,1,0],[4,6,5]], dtype='f4')
print ("========sort========")
print (np.sort(a))
print (np.sort(a, axis=0)) #행 기준 정렬
print (np.sort(a, axis=1)) #열 기준 정렬

print ("========arg sort========")
b = np.array([[2,0,1]], dtype='f4')
print (np.argsort(b)) #정렬된 행렬의 index 반환


========sort========
[[ 0.  1.  2.]
 [ 4.  5.  6.]]
[[ 2.  1.  0.]
 [ 4.  6.  5.]]
[[ 0.  1.  2.]
 [ 4.  5.  6.]]
========arg sort========
[[1 2 0]]


## Numpy 슬라이싱

각 차원별로 배열 슬라이싱 지원

In [11]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print ("========slicing========")
print (a)
print (a[0,:])
print (a[1,:])
print (a[1,1:2])
print (a[1,1:-1])
print (a[:,0])
print (a[0,1:])

x = sum(a[1,])
print x

========slicing========
[[0 1 2 3]
 [4 5 6 7]]
[0 1 2 3]
[4 5 6 7]
[5]
[5 6]
[0 4]
[1 2 3]
22


## Numpy 브로드캐스팅 

numpy에서 배열 형태가 다른 경우 연산하는 방법

In [12]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.zeros_like(x)

# [1,2,3] + [1,0,1]
# [4,5,6] + [1,0,1]
# [7,8,9] + [1,0,1]
# [10,11,12] + [1,0,1]
# for 문을 사용할 경우 성능이 떨어짐
print ("========for loop========")
for i in range(4):
    y[i, :] = x[i, :] + v
print (y)

print ("========tile========")
#[1,0,1]을 쌓은 후 연산
vv = np.tile(v, (4,1))
print (vv)

y = x + vv
print (y)

========for loop========
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
========tile========
[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [13]:
print ("========broadcasting========")
#numpy 브로드 캐스팅
y = x + v
print (y)

a = np.array([[0],[10],[20],[30]])
b = np.array([0,1,2])
print (a + b)

'''
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 2])
print (x + v)
'''

========broadcasting========
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


'\nx = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])\nv = np.array([1, 2])\nprint (x + v)\n'

## Numpy 배열 변환
배열의 shape 변경

* transpose
* reshape, flatten
* newaxis
* stack

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]])

#numpy array transpose, (2,3) -> (3,2)
print ("========transpose========")
print (a)
print (a.T)

#reshape
print ("========reshape========")
print (a.reshape(1,6))
print (a.reshape(6,1))
print (a.reshape(1,-1))


========transpose========
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
========reshape========
[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [16]:

print ("========flatten========")
print (a.flatten())

print ("========newaxis========")
b = np.array([1,2,3,4,5,6])
print (b)
b = np.transpose(b)
print (b)
print (b[:, np.newaxis])


========flatten========
[1 2 3 4 5 6]
========newaxis========
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [17]:
a = np.array([1,2,3])
b = np.array([4,5])
print ("========concatenate========")
print (np.concatenate([a,b]))

# 배열을 가로로 연결
a = np.zeros((2,3))
b = np.zeros((2,2))
print ("========hstack========")
print (a)
print (b)
print (np.hstack([a,b]))


========concatenate========
[1 2 3 4 5]
========hstack========
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]


In [18]:

# 배열을 세로로 연결
a = np.zeros((3,2))
b = np.zeros((2,2))
print ("========vstack========")
print (a)
print (b)
print (np.vstack([a,b]))


========vstack========
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [19]:

#가장 안쪽 차원 삽입하며 연결
a = np.ones((4,5))
b = np.zeros((4,5))
print ("========dstack========")
print (a)
print (b)
print (np.dstack([a,b]))
print (np.dstack([a,b]).shape)

========dstack========
[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[[ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]]

 [[ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]]

 [[ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]]

 [[ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]
  [ 1.  0.]]]
(4, 5, 2)


In [20]:
#지정한 차원으로 새로운 차원 삽입하며 연결
print ("========stack========")
print (np.stack([a, b], axis=1))
print (np.stack([a, b], axis=1).shape)
print (np.stack([a, b], axis=0))
print (np.stack([a, b], axis=0).shape)

========stack========
[[[ 1.  1.  1.  1.  1.]
  [ 0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.]
  [ 0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.]
  [ 0.  0.  0.  0.  0.]]

 [[ 1.  1.  1.  1.  1.]
  [ 0.  0.  0.  0.  0.]]]
(4, 2, 5)
[[[ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]
  [ 1.  1.  1.  1.  1.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]]
(2, 4, 5)


In [21]:

#첫번째 열 기준 연결 indexer
a = np.zeros((2,3))
b = np.ones((2,3))
print ("========r_========")
print (np.r_[a,b])
print (np.r_[a,b].shape)

#두번째 열 기준 연결 indexer
print ("========c_========")
print (np.c_[a,b])
print (np.c_[a,b].shape)

#동일한 배열을 반복
print ("========tile========")
print (a)
print (np.tile(a, 2))
print (np.tile(a, (3,2)))

========r_========
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
(4, 3)
========c_========
[[ 0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.]]
(2, 6)
========tile========
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


## Numpy 좌표 생성
numpy meshgrid를 사용하여 좌표 생성

In [ ]:
x = np.array([0,1,2,3,4,5])
y = np.array([0,1,2,3])

X, Y = np.meshgrid(x,y)
print (X)
print (Y)

grid = np.vstack([X,Y]).reshape(2,-1).T
print (grid)
    
import matplotlib.pyplot as plt
plt.scatter(X, Y, linewidths=10)
plt.show()

## Numpy 역함수 
numpy 함수를 사용하여 행렬의 역함수를 구해본다.
![title2](./inv.gif)

In [ ]:
a = np.array([[1., 2.], [3., 4.]])
ainv = np.linalg.inv(a)
print (ainv)
print (np.dot(a, ainv))
print (np.eye(2))